### PR TITLE
Fix ticker models

### PR DESCRIPTION
**Pull request by ddeath**
Fix ticker models.

Why the test does not run against real api?

### CODE REVIEW

**Comment by ddeath** [comment]
I see that you removed that a day ago. My question is why if the node library is not working at the moment with the removed symbol.

**Comment by fieldfoxWim** [comment]
Just saw your pull request after I created an issue for it. #10 

Culprit commit [2b46b6c](https://github.com/bitfinexcom/bfx-api-node-models/commit/2b46b6cea02f385003a6d12c757e76710bcf2204)
by @leehillz 

@leehillz please advice

**Comment by f3rno** [comment]
I cannot reproduce on latest `master` of this repo, nor with the latest released version. Can you confirm it is still an issue if you run `npm update bfx-api-node-models` in your project repos?

**Comment by f3rno** [comment]
@JacobPlaster can be closed I think

**Pull request closed without merging**
